server:
  port: 8081
spring:
  datasource:
    url: ENC(5PeBklAf+Z6lun3ZEFq862L9zcFw5Vvaj+LVjwqPpIH7qB8ymb1X1fKl7hvVg7rWHXTSvVSgZj5hdEwbvKtL1fbxsoWYzkIFi+taNkyxUwnT8nIUdQa2EqnJcG8WVU1VwQo9rPDl43dHy1nza2m2ogyt6w+tj7k8L2fEl3RuTjc=)
    driver-class-name: org.postgresql.Driver
#  data:
#    redis:
#      host: redis
#      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false

jwt:
  secretKey: wpdlejqmfdbxl
  accessExpiration: 300000
  refreshExpiration: 600000
  aesKey: aesEncryptKeyeee
#
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}