server:
  port: 8081
spring:
  datasource:
    url: ENC(17SHYt5RCAUf6KpSShtZjgcSevBkwT+GbCPWZxDDBkoyw2ZgfZncx81uxgTIVRWds+PE62f2z0ppBZScofnIkvgd6+IhMmJM6Tf7qC2XN5fN9/GKKbov6Q==)
    username: ENC(lB7dmns7qvY2+qe7qLo/t1+yFTO1yjTk)
    password: ENC(x0+kZwYDVNYwmFGkk/bUPDEvyizg+wGg)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false

  jwt:
    secret: ENC(FT9pgO6cJqjr0IExg4aQ4ImDHu4W9Q2N)
    accessTokenExpiration: 300000
    refreshTokenExpiration: 600000
jasypt:
  encryptor:
    bean: jasyptStringEncryptor